layout_spectrum: 0.3117902837693691
typography_spectrum: 0.5788641418330371
color:
  brandStrength: 0.885092044249177
  lightness: 0.2609089764300734
  saturation: 0.17630775552242994
  rhythmicContrast: 0.7616623979993165
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
name: Northish
